version: 2.1

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/python:3.7.7
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
    - run: sudo apt install tree
    - run: tree
    - run:
        command: |
          sudo pip install pipenv
          pipenv install
    - run: 
        command: |
          cd tests
          pipenv run python -m unittest